--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/cosmicnebula200/FunBlockLuckyBlock
build-by-default: true
branches:
- main
projects:
  FunBlockLuckyBlock:
    path: ""
    libs:
      - src: CortexPE/Commando/Commando
        version: ^3.0.0
        branch: PM4
      - src: muqsit/simplepackethandler/SimplePacketHandler
      version: ^0.0.1
...
