# The default config for FunBlockLuckyBlock by cosmicnebula200
version: 1.0.0

# Available modes
# - blacklist
# - whitelist
mode: blacklist

worlds:
  - 'world1'
  - 'world2'

luckyblock:
  block-id: 247
  item-id: 247
  hardness: 5